dist: trusty

language: php

## Cache composer and apt downloads.
cache:
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

php:
  - 5.4
  - 7.3

jobs:
  fast_finish: true


before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

  # --prefer-dist will allow for optimal use of the travis caching ability.
  - composer install --prefer-dist --no-suggest


script:
  # Validate the composer.json file on low/high PHP versions.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict
